image: tetraweb/php:7.1

variables:
  SIMPLETEST_DB: "sqlite://tmp/site.sqlite"
  SIMPLETEST_BASE_URL: "http://127.0.0.1:8080"

cache:
  paths:
  - vendor/

before_script:
  - php -m
  - docker-php-ext-enable gd zip

build:
  stage: build
  script:
    - composer install

phpunit:
  stage: test
  script:
    - ls
    - php vendor/bin/phpunit -c core core/tests/Drupal/Tests/Core/Password/PasswordHashingTest.php
    - php vendor/bin/phpunit -c web/core web/core/tests/Drupal/Tests/Core/Password/PasswordHashingTest.php
  
#    services:
#    - tetraweb/mysql


#script:
#  - cd $TRAVIS_BUILD_DIR
#  - vendor/bin/behat --profile travis    
#    
#deploy:
#  artifacts:
#    paths:
#    - build/
## only:
#    - dev
#  script:
#    - ssh-add <(echo "$STAGING_PRIVATE_KEY")
#    - ssh -p22 server_user@server_host "mkdir htdocs/wp-content/themes/_tmp"
#    - scp -P22 -r build/* server_user@server_host:htdocs/wp-content/themes/_tmp
#    - ssh -p22 server_user@server_host "mv htdocs/wp-content/themes/live htdocs/wp-content/themes/_old && mv htdocs/wp-content/themes/_tmp htdocs/wp-content/themes/live"
#    - ssh -p22 server_user@server_host "rm -rf htdocs/wp-content/themes/_old"