name: php

type: php:5.6

runtime:
   extensions:
      - imap

build:
    flavor: composer

relationships:
    database: "mysql:mysql"

dependencies:
    php:
        "drush/drush": "dev-master"

web:
    document_root: "/public"
    passthru: "/index.php"

disk: 2048

mounts:
    "/public/sites/default/files": "shared:files/files"
    "/tmp": "shared:files/tmp"
    "/config": "shared:files/config"
    "/private": "shared:files/private"

hooks:
    build: |
        cd public
        # Install the latest Composer.
        if [ ! -z "$COMPOSER_HOME" ]; then
          curl -sS https://getcomposer.org/installer | php
          mkdir -p "$COMPOSER_HOME"/bin
          mv composer.phar "$COMPOSER_HOME"/bin/composer
        fi

        # Create Drupal in a temporary folder.
        #composer create-project drupal-composer/drupal-project:8.x-dev drupal-tmp --stability dev --no-interaction

        # Move Drupal (via recursive rsync) into the 'drupal' folder.
        #rsync -a drupal-tmp/* drupal
        #rm -r drupal-tmp

        # Install the settings.php file.
        mv settings.php /public/settings.php
    deploy: |
        cd $PLATFORM_DOCUMENT_ROOT
        drush cr
        drush -y updatedb

crons:
    drupal:
        spec: "*/20 * * * *"
        cmd: "drush -r $PLATFORM_DOCUMENT_ROOT core-cron"
